console.log("=========Bank Name=========");
var bankName;
console.log("Bank Name is: ", bankName);
bankName = "SBI Bank";
console.log("Bank Name is: ", bankName);
console.log("Data Type of Bank Name is: ", typeof bankName);
console.log("=========Marks=========");
var marks = "90%";
console.log("Marks: ", marks);
console.log("Data Type of Marks is: ", typeof marks);
console.log("=========Working=========");
var isWorking;
console.log("is working: ", isWorking);
console.log("Data Type of isworking is: ", typeof isWorking);
isWorking = true;
console.log("is working: ", isWorking);
console.log("Data Type of isworking is: ", typeof isWorking);
console.log("=========Total Count=========");
var count = "Hundred and seven";
console.log("Total Count is: ", count);
console.log("Data Type of count is: ", typeof count);
count = 107;
console.log("count is in number: ", count);
console.log("Data Type of count is: ", typeof count);
